package grails.plugin.awssdk.test

import com.amazonaws.services.dynamodbv2.datamodeling.*
import groovy.transform.ToString

@DynamoDBTable(tableName="FooItem")
@ToString(includeNames=true, includeFields=true)
class FooItem {

    @DynamoDBHashKey
    Long accountId // Hash key
    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    String id // Range key, with an automatically generated ID

    @DynamoDBAttribute
    int count = 0
    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(localSecondaryIndexName="creationDate")
    Date creationDate
    @DynamoDBAttribute
    String message
    @DynamoDBAttribute
    String title

}
