name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: gradle
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Publish plugins
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish -Pversion=${{ steps.version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          DEPLOYER_PASSWORD: ${{ secrets.DEPLOYER_PASSWORD }}
  ping:
    name: Notify Upstream Repositories
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      matrix:
        repository:
          - agorapulse/agorapulse-bom
          - agorapulse/agorapulse-oss
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Dispatch to ${{ matrix.repository }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.AGORAPULSE_BOT_PERSONAL_TOKEN }}
          repository: ${{ matrix.repository }}
          event-type: ap-new-version-released-event
          client-payload: '{ "group": "com.agorapulse", "module": "grails-aws-sdk", "version": "${{ steps.version.outputs.tag }}", "property": "grails.aws.sdk.version", "github" : ${{ toJson(github) }} }'
